name: Python Filesystem GitHub Actions Workflow

on:
  push:
    branches:
      - main
env:
  AWS_REGION: "us-east-2"
  CURRENT_BRANCH: ${{  github.base_ref || github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment: pypi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Update version in pyproject.toml
        run: |
           sed -i "s/^version = \"\([0-9]*\.[0-9]*\.[0-9]*\)\"/version = \"\1.${{ github.run_number }}\"/" pyproject.toml

      - name: Run tests
        run: poetry run pytest tests

      - name: Build package
        run: poetry build

      - name: Publish package distributions to PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
